name: Environment Variables
on: push
env:
  WF_ENV: Available to all jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available only to steps in this job
    steps:
      - name: Log env Variables
        env:
          STEP_ENV: Available only to one step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log env Variables
        env:
          STEP_ENV: Available only to one step
        run: |
          echo "GIHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
